import { useEffect, useRef } from 'react'
import { LEGAL } from '../data/legal'

interface LegalOverlayProps {
  onClose: () => void
}

export function LegalOverlay({ onClose }: LegalOverlayProps) {
  const closeRef = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    closeRef.current?.focus()
    function onKey(e: KeyboardEvent): void {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  return (
    <div className="legal-overlay" role="dialog" aria-modal="true" aria-label="Legal information">
      <div className="legal-inner">
        <button ref={closeRef} type="button" className="legal-close" onClick={onClose}>
          close ×
        </button>

        <h1 className="legal-title">Legal</h1>

        <section className="legal-section">
          <h2>Publisher</h2>
          <p>
            {LEGAL.publisherName}
            <br />
            {LEGAL.publisherAddress}
            <br />
            {LEGAL.publisherEmail} &middot; {LEGAL.publisherPhone}
          </p>
          <p>{LEGAL.publisherSiret}</p>
        </section>

        <section className="legal-section">
          <h2>Hosting</h2>
          <p>
            {LEGAL.hostName}
            <br />
            {LEGAL.hostAddress}
            <br />
            {LEGAL.hostPhone}
          </p>
        </section>

        <section className="legal-section">
          <h2>Privacy</h2>
          <p>
            Your preferences (spin count, twists and sound settings) are stored only in your
            browser&rsquo;s localStorage and never leave your device. There are no accounts, no
            forms, no tracking, no sponsored content and no affiliate links in this version.
          </p>
          <p>
            The hosting provider (GitHub Pages) may keep standard server logs for security
            purposes.
          </p>
          <p>Questions about this page: {LEGAL.publisherEmail}</p>
        </section>

        <section className="legal-section">
          <h2>Disclaimer</h2>
          <p>
            Ideas generated by Vibe Roulette are provided as-is for inspiration only, with no
            guarantee of originality, viability or commercial success. Validate any idea before
            investing time or money.
          </p>
        </section>
      </div>
    </div>
  )
}
